CREATE TABLE Customer (
    CustomerID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    FirstName TEXT NOT NULL,
    LastName TEXT NOT NULL,
    Email TEXT NOT NULL,
    Birthday DATE NOT NULL,
    Points INTEGER NOT NULL
);

CREATE TABLE `Order` (
    OrderID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    ShopID INTEGER NOT NULL,
    CustomerID INTEGER NOT NULL,
    FOREIGN KEY (ShopID) REFERENCES Shop (ShopID),
    FOREIGN KEY (CustomerID) REFERENCES Customer (CustomerID)
);

CREATE TABLE CookieOrder (
    OrderID INTEGER NOT NULL,
    CookieID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    Amount INTEGER NOT NULL,
    FOREIGN KEY (OrderID) REFERENCES `Order` (OrderID)
);

CREATE TABLE Cookie (
    CookieID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    Type TEXT NOT NULL,
    CookieName TEXT NOT NULL,
    GlutenFree BOOLEAN NOT NULL,
    DairyFree BOOLEAN NOT NULL
);

CREATE TABLE Shop (
    ShopID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    AddressID INTEGER NOT NULL,
    PhoneNumber TEXT NOT NULL,
    FOREIGN KEY (AddressID) REFERENCES Address (AddressID)
);

CREATE TABLE CookieShop (
    ShopID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    CookieID INTEGER NOT NULL,
    FOREIGN KEY (CookieID) REFERENCES Cookie (CookieID)
);

CREATE TABLE Address (
    AddressID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    State TEXT NOT NULL,
    Zip INTEGER NOT NULL,
    City TEXT NOT NULL
);

-- Add constraints
PRAGMA foreign_keys = ON;
